"""Add company column to Budget

Revision ID: 06566c7081b0
Revises: 
Create Date: 2024-11-30 00:02:25.786907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06566c7081b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###
